### ISSUE TITLE
Add possibility to use discrete numbers for x instead of a range

### ISSUE THREAD

**Issue by bubendorf** [siggel/coordinatejoker#17]
Often the question in the geocaching listing gives some answers together with a number. So it would be fine if I could enter these discrete numbers instead of the range to be used for x.

**Comment by siggel** [comment]
Thx for the input. For the very first version I wanted to keep things simple. At least for Locus the waypoints will show the x value on mouse over so you can easily filter the discrete values.
But I understand the need and will consider your suggestion. I need to think about how to enable it while keeping a simple usability not overloading the UI with too many options. A first idea is entering it like pages in print menu ("1-3" or "1,3") but I should take care in case of negative numbers

**Comment by siggel** [comment]
implementation provided by bubendorf via pull request, thx
