### ISSUE TITLE
Add second variable: y

### ISSUE THREAD

**Issue by bubendorf** [siggel/coordinatejoker#18]
Often not only one stage/answer is unknown, but two.
It would be fine to have an additional variable, y.
y should have its own range / discrete values.

Waypoints are then generated for all combinations of all x and y values. Of course there must be an upper limit of the number of generated waypoints.

Optional: A third variable z. But this is only seldom necessary!

**Comment by siggel** [comment]
Indeed this would have been helpful for myself today :)
However I'm a bit afraid the app might be used quite often for cheating mysteries if it offers too many variables.
So I may need some time to consider pros and cons before adding this ;)

**Comment by siggel** [comment]
bubendorf implemented it and convinced me
