### ISSUE TITLE
F-droid inclusion

### ISSUE THREAD

**Issue by Lomanic** [siggel/coordinatejoker#50]
Great work on Coordinate Joker, it fits a need I had more than once. Would you mind your app being served through the opensource/free repository [f-droid.org](https://f-droid.org)? I think the app fits perfectly the f-droid requirements (no closed source dependencies, copyleft licence).

**Comment by siggel** [comment]
Sorry, realized this issue with some months delay... I cannot afford it to maintain it on f-droid too, but anyone would be free to maintain a copy there. All I could do is provide sources here like done already and the apk. However, Play console meanwhile does not provide a "generic" signed apk anymore for download so I could only provide a self signed apk at each release here and someone else would need to bring that to f-droid and do proper signing.

**Comment by Lomanic** [comment]
f-droid.org builds apps from source, the requirements are quite light I think it would be simple to bring this app there, as I see it it doesn't add any maintenance (it should be a one time job).

I see see you already tag releases, so f-droid can build your app automatically when a new release is tagged (no need to provide apks on your part).

As I read some inclusions requests like in https://github.com/WangDaYeeeeee/GeometricWeather/issues/9#issuecomment-603627898, I think it's only required for this app to be included in f-droid repo to provide metadata (can be fastlane structure) for the f-droid repo, and a request for packaging in https://gitlab.com/fdroid/rfp.

Would you be interested in a PR that provides metadata in your repo and would you be OK for its inclusion in f-droid? Once merged and the rfp against f-droid repo accepted and merged, f-droid would build, sign and release a new apk automatically on their repo without any more action on your part than currently.

**Comment by siggel** [comment]
I submitted a request for packaging, see https://gitlab.com/fdroid/rfp/-/issues/1635

**Comment by fossdd** [comment]
Yes, we need fastlane structures, to get metadata. [More on my comment on your RFP](https://gitlab.com/fdroid/rfp/-/issues/1635#note_499506498)

**Comment by siggel** [comment]
Details see https://gitlab.com/fdroid/rfp/-/issues/1635

**Comment by siggel** [comment]
available on F-Droid now
