### ISSUE TITLE
joker caches can't be deleted in c:geo

### ISSUE THREAD

**Issue by 7eter** [siggel/coordinatejoker#61]
So I created a few caches with the "Coordinate Joker" App. Imported them to c:geo in a separate list named 'joker' - as advised.
After deleting the caches from the list they still appear on my 'live map'.
Clearing the cache of c:geo didn't help either.
Any ideas?

**Comment by siggel** [comment]
This is a known ("wanted") issue in c:geo. Just wait for 72hours. For details see https://github.com/cgeo/cgeo/issues/7648
