### ISSUE TITLE
Fix app description on F-Droid

### ISSUE THREAD

**Issue by Korb** [siggel/coordinatejoker#66]
![Coordinate Joker](https://user-images.githubusercontent.com/3509797/222976790-8886f892-456d-4caf-8f25-ad18b9db23b6.png)

(highlighted in red)

**Comment by siggel** [comment]
fixed with (F-Droid only) version 1.3.32, no recompile for Google Play store necessary

**Comment by siggel** [comment]
App's changelog html files are now converted to plaintext fastlane changelog files by removing the html tags and whitespace. The files state the version as first line intentionally, as the changelogs also cover versions, that have not been published, so a version x file may contain sections for versions x and x-1.

**Comment by siggel** [comment]
@IzzySoft I still to not see the version 1.3.32 on F-Droid and do not remember where I could see the build status of my release to have a look whether I need to fix anything. Or did I miss any step (I only remember roughly, that my normal procedure of tagging and releasing was sufficient for triggering fastlane) or does it just take some time until fastlane contributions will be merged?
